
set_property IOSTANDARD LVCMOS33 [get_ports test_out2]
set_property PACKAGE_PIN R17 [get_ports test_out2]

set_property IOSTANDARD LVCMOS33 [get_ports adc_clk]
set_property PACKAGE_PIN T14 [get_ports {adc_in[0]}]
set_property PACKAGE_PIN P14 [get_ports {adc_in[1]}]
set_property PACKAGE_PIN Y17 [get_ports adc_clk]
set_property PACKAGE_PIN T15 [get_ports {adc_in[2]}]
set_property PACKAGE_PIN R14 [get_ports {adc_in[3]}]
set_property PACKAGE_PIN R19 [get_ports {adc_in[4]}]
set_property PACKAGE_PIN V12 [get_ports {adc_in[5]}]
set_property PACKAGE_PIN V13 [get_ports {adc_in[6]}]
set_property PACKAGE_PIN W13 [get_ports {adc_in[7]}]
set_property PACKAGE_PIN T11 [get_ports {adc_in[8]}]
set_property PACKAGE_PIN T12 [get_ports {adc_in[9]}]
set_property PACKAGE_PIN T10 [get_ports {adc_in[10]}]
set_property PACKAGE_PIN U12 [get_ports {adc_in[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_in[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_in[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_in[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_in[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_in[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_in[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_in[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_in[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_in[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_in[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_in[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_in[0]}]

set_property PACKAGE_PIN M17 [get_ports adc_ovr_led_n]
set_property IOSTANDARD LVCMOS18 [get_ports adc_ovr_led_n]
