// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="sound_sender_sound_sender,hls_ip_2022_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z010-clg400-1,HLS_INPUT_CLOCK=25.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=18.250000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=862,HLS_SYN_LUT=1803,HLS_VERSION=2022_2}" *)

module sound_sender (
        ap_clk,
        ap_rst_n,
        in_bus_TDATA,
        in_bus_TVALID,
        in_bus_TREADY,
        in_bus_TKEEP,
        in_bus_TSTRB,
        in_bus_TUSER,
        in_bus_TLAST,
        m_axi_out_bus_AWVALID,
        m_axi_out_bus_AWREADY,
        m_axi_out_bus_AWADDR,
        m_axi_out_bus_AWID,
        m_axi_out_bus_AWLEN,
        m_axi_out_bus_AWSIZE,
        m_axi_out_bus_AWBURST,
        m_axi_out_bus_AWLOCK,
        m_axi_out_bus_AWCACHE,
        m_axi_out_bus_AWPROT,
        m_axi_out_bus_AWQOS,
        m_axi_out_bus_AWREGION,
        m_axi_out_bus_AWUSER,
        m_axi_out_bus_WVALID,
        m_axi_out_bus_WREADY,
        m_axi_out_bus_WDATA,
        m_axi_out_bus_WSTRB,
        m_axi_out_bus_WLAST,
        m_axi_out_bus_WID,
        m_axi_out_bus_WUSER,
        m_axi_out_bus_ARVALID,
        m_axi_out_bus_ARREADY,
        m_axi_out_bus_ARADDR,
        m_axi_out_bus_ARID,
        m_axi_out_bus_ARLEN,
        m_axi_out_bus_ARSIZE,
        m_axi_out_bus_ARBURST,
        m_axi_out_bus_ARLOCK,
        m_axi_out_bus_ARCACHE,
        m_axi_out_bus_ARPROT,
        m_axi_out_bus_ARQOS,
        m_axi_out_bus_ARREGION,
        m_axi_out_bus_ARUSER,
        m_axi_out_bus_RVALID,
        m_axi_out_bus_RREADY,
        m_axi_out_bus_RDATA,
        m_axi_out_bus_RLAST,
        m_axi_out_bus_RID,
        m_axi_out_bus_RUSER,
        m_axi_out_bus_RRESP,
        m_axi_out_bus_BVALID,
        m_axi_out_bus_BREADY,
        m_axi_out_bus_BRESP,
        m_axi_out_bus_BID,
        m_axi_out_bus_BUSER,
        interrupt_out,
        interrupt_out_ap_vld
);

parameter    ap_ST_fsm_state1 = 21'd1;
parameter    ap_ST_fsm_state2 = 21'd2;
parameter    ap_ST_fsm_state3 = 21'd4;
parameter    ap_ST_fsm_state4 = 21'd8;
parameter    ap_ST_fsm_state5 = 21'd16;
parameter    ap_ST_fsm_state6 = 21'd32;
parameter    ap_ST_fsm_state7 = 21'd64;
parameter    ap_ST_fsm_state8 = 21'd128;
parameter    ap_ST_fsm_state9 = 21'd256;
parameter    ap_ST_fsm_state10 = 21'd512;
parameter    ap_ST_fsm_state11 = 21'd1024;
parameter    ap_ST_fsm_state12 = 21'd2048;
parameter    ap_ST_fsm_state13 = 21'd4096;
parameter    ap_ST_fsm_state14 = 21'd8192;
parameter    ap_ST_fsm_state15 = 21'd16384;
parameter    ap_ST_fsm_state16 = 21'd32768;
parameter    ap_ST_fsm_state17 = 21'd65536;
parameter    ap_ST_fsm_state18 = 21'd131072;
parameter    ap_ST_fsm_state19 = 21'd262144;
parameter    ap_ST_fsm_state20 = 21'd524288;
parameter    ap_ST_fsm_state21 = 21'd1048576;
parameter    C_M_AXI_OUT_BUS_ID_WIDTH = 1;
parameter    C_M_AXI_OUT_BUS_ADDR_WIDTH = 32;
parameter    C_M_AXI_OUT_BUS_DATA_WIDTH = 32;
parameter    C_M_AXI_OUT_BUS_AWUSER_WIDTH = 1;
parameter    C_M_AXI_OUT_BUS_ARUSER_WIDTH = 1;
parameter    C_M_AXI_OUT_BUS_WUSER_WIDTH = 1;
parameter    C_M_AXI_OUT_BUS_RUSER_WIDTH = 1;
parameter    C_M_AXI_OUT_BUS_BUSER_WIDTH = 1;
parameter    C_M_AXI_OUT_BUS_TARGET_ADDR = 0;
parameter    C_M_AXI_OUT_BUS_USER_VALUE = 0;
parameter    C_M_AXI_OUT_BUS_PROT_VALUE = 0;
parameter    C_M_AXI_OUT_BUS_CACHE_VALUE = 3;
parameter    C_M_AXI_DATA_WIDTH = 32;

parameter C_M_AXI_OUT_BUS_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input  [31:0] in_bus_TDATA;
input   in_bus_TVALID;
output   in_bus_TREADY;
input  [3:0] in_bus_TKEEP;
input  [3:0] in_bus_TSTRB;
input  [15:0] in_bus_TUSER;
input  [0:0] in_bus_TLAST;
output   m_axi_out_bus_AWVALID;
input   m_axi_out_bus_AWREADY;
output  [C_M_AXI_OUT_BUS_ADDR_WIDTH - 1:0] m_axi_out_bus_AWADDR;
output  [C_M_AXI_OUT_BUS_ID_WIDTH - 1:0] m_axi_out_bus_AWID;
output  [7:0] m_axi_out_bus_AWLEN;
output  [2:0] m_axi_out_bus_AWSIZE;
output  [1:0] m_axi_out_bus_AWBURST;
output  [1:0] m_axi_out_bus_AWLOCK;
output  [3:0] m_axi_out_bus_AWCACHE;
output  [2:0] m_axi_out_bus_AWPROT;
output  [3:0] m_axi_out_bus_AWQOS;
output  [3:0] m_axi_out_bus_AWREGION;
output  [C_M_AXI_OUT_BUS_AWUSER_WIDTH - 1:0] m_axi_out_bus_AWUSER;
output   m_axi_out_bus_WVALID;
input   m_axi_out_bus_WREADY;
output  [C_M_AXI_OUT_BUS_DATA_WIDTH - 1:0] m_axi_out_bus_WDATA;
output  [C_M_AXI_OUT_BUS_WSTRB_WIDTH - 1:0] m_axi_out_bus_WSTRB;
output   m_axi_out_bus_WLAST;
output  [C_M_AXI_OUT_BUS_ID_WIDTH - 1:0] m_axi_out_bus_WID;
output  [C_M_AXI_OUT_BUS_WUSER_WIDTH - 1:0] m_axi_out_bus_WUSER;
output   m_axi_out_bus_ARVALID;
input   m_axi_out_bus_ARREADY;
output  [C_M_AXI_OUT_BUS_ADDR_WIDTH - 1:0] m_axi_out_bus_ARADDR;
output  [C_M_AXI_OUT_BUS_ID_WIDTH - 1:0] m_axi_out_bus_ARID;
output  [7:0] m_axi_out_bus_ARLEN;
output  [2:0] m_axi_out_bus_ARSIZE;
output  [1:0] m_axi_out_bus_ARBURST;
output  [1:0] m_axi_out_bus_ARLOCK;
output  [3:0] m_axi_out_bus_ARCACHE;
output  [2:0] m_axi_out_bus_ARPROT;
output  [3:0] m_axi_out_bus_ARQOS;
output  [3:0] m_axi_out_bus_ARREGION;
output  [C_M_AXI_OUT_BUS_ARUSER_WIDTH - 1:0] m_axi_out_bus_ARUSER;
input   m_axi_out_bus_RVALID;
output   m_axi_out_bus_RREADY;
input  [C_M_AXI_OUT_BUS_DATA_WIDTH - 1:0] m_axi_out_bus_RDATA;
input   m_axi_out_bus_RLAST;
input  [C_M_AXI_OUT_BUS_ID_WIDTH - 1:0] m_axi_out_bus_RID;
input  [C_M_AXI_OUT_BUS_RUSER_WIDTH - 1:0] m_axi_out_bus_RUSER;
input  [1:0] m_axi_out_bus_RRESP;
input   m_axi_out_bus_BVALID;
output   m_axi_out_bus_BREADY;
input  [1:0] m_axi_out_bus_BRESP;
input  [C_M_AXI_OUT_BUS_ID_WIDTH - 1:0] m_axi_out_bus_BID;
input  [C_M_AXI_OUT_BUS_BUSER_WIDTH - 1:0] m_axi_out_bus_BUSER;
output   interrupt_out;
output   interrupt_out_ap_vld;

reg interrupt_out_ap_vld;

 reg    ap_rst_n_inv;
reg   [8:0] burst_count_reg;
reg   [15:0] test_irq_cnt;
reg    out_bus_blk_n_AW;
(* fsm_encoding = "none" *) reg   [20:0] ap_CS_fsm;
wire    ap_CS_fsm_state3;
reg    out_bus_blk_n_B;
wire    ap_CS_fsm_state10;
reg   [8:0] select_ln67_reg_311;
reg    out_bus_blk_n_W;
wire    ap_CS_fsm_state17;
wire    ap_CS_fsm_state16;
wire    ap_CS_fsm_state11;
wire  signed [22:0] or_ln_fu_233_p3;
reg   [22:0] or_ln_reg_301;
wire   [8:0] select_ln67_fu_267_p3;
wire    ap_CS_fsm_state9;
reg   [3:0] data_buf_address0;
reg    data_buf_ce0;
reg    data_buf_we0;
wire   [31:0] data_buf_q0;
wire    grp_sound_sender_Pipeline_VITIS_LOOP_48_1_fu_171_ap_start;
wire    grp_sound_sender_Pipeline_VITIS_LOOP_48_1_fu_171_ap_done;
wire    grp_sound_sender_Pipeline_VITIS_LOOP_48_1_fu_171_ap_idle;
wire    grp_sound_sender_Pipeline_VITIS_LOOP_48_1_fu_171_ap_ready;
wire    grp_sound_sender_Pipeline_VITIS_LOOP_48_1_fu_171_in_bus_TREADY;
wire   [3:0] grp_sound_sender_Pipeline_VITIS_LOOP_48_1_fu_171_data_buf_address0;
wire    grp_sound_sender_Pipeline_VITIS_LOOP_48_1_fu_171_data_buf_ce0;
wire    grp_sound_sender_Pipeline_VITIS_LOOP_48_1_fu_171_data_buf_we0;
wire   [31:0] grp_sound_sender_Pipeline_VITIS_LOOP_48_1_fu_171_data_buf_d0;
wire    grp_sound_sender_Pipeline_2_fu_186_ap_start;
wire    grp_sound_sender_Pipeline_2_fu_186_ap_done;
wire    grp_sound_sender_Pipeline_2_fu_186_ap_idle;
wire    grp_sound_sender_Pipeline_2_fu_186_ap_ready;
wire    grp_sound_sender_Pipeline_2_fu_186_m_axi_out_bus_AWVALID;
wire   [31:0] grp_sound_sender_Pipeline_2_fu_186_m_axi_out_bus_AWADDR;
wire   [0:0] grp_sound_sender_Pipeline_2_fu_186_m_axi_out_bus_AWID;
wire   [31:0] grp_sound_sender_Pipeline_2_fu_186_m_axi_out_bus_AWLEN;
wire   [2:0] grp_sound_sender_Pipeline_2_fu_186_m_axi_out_bus_AWSIZE;
wire   [1:0] grp_sound_sender_Pipeline_2_fu_186_m_axi_out_bus_AWBURST;
wire   [1:0] grp_sound_sender_Pipeline_2_fu_186_m_axi_out_bus_AWLOCK;
wire   [3:0] grp_sound_sender_Pipeline_2_fu_186_m_axi_out_bus_AWCACHE;
wire   [2:0] grp_sound_sender_Pipeline_2_fu_186_m_axi_out_bus_AWPROT;
wire   [3:0] grp_sound_sender_Pipeline_2_fu_186_m_axi_out_bus_AWQOS;
wire   [3:0] grp_sound_sender_Pipeline_2_fu_186_m_axi_out_bus_AWREGION;
wire   [0:0] grp_sound_sender_Pipeline_2_fu_186_m_axi_out_bus_AWUSER;
wire    grp_sound_sender_Pipeline_2_fu_186_m_axi_out_bus_WVALID;
wire   [31:0] grp_sound_sender_Pipeline_2_fu_186_m_axi_out_bus_WDATA;
wire   [3:0] grp_sound_sender_Pipeline_2_fu_186_m_axi_out_bus_WSTRB;
wire    grp_sound_sender_Pipeline_2_fu_186_m_axi_out_bus_WLAST;
wire   [0:0] grp_sound_sender_Pipeline_2_fu_186_m_axi_out_bus_WID;
wire   [0:0] grp_sound_sender_Pipeline_2_fu_186_m_axi_out_bus_WUSER;
wire    grp_sound_sender_Pipeline_2_fu_186_m_axi_out_bus_ARVALID;
wire   [31:0] grp_sound_sender_Pipeline_2_fu_186_m_axi_out_bus_ARADDR;
wire   [0:0] grp_sound_sender_Pipeline_2_fu_186_m_axi_out_bus_ARID;
wire   [31:0] grp_sound_sender_Pipeline_2_fu_186_m_axi_out_bus_ARLEN;
wire   [2:0] grp_sound_sender_Pipeline_2_fu_186_m_axi_out_bus_ARSIZE;
wire   [1:0] grp_sound_sender_Pipeline_2_fu_186_m_axi_out_bus_ARBURST;
wire   [1:0] grp_sound_sender_Pipeline_2_fu_186_m_axi_out_bus_ARLOCK;
wire   [3:0] grp_sound_sender_Pipeline_2_fu_186_m_axi_out_bus_ARCACHE;
wire   [2:0] grp_sound_sender_Pipeline_2_fu_186_m_axi_out_bus_ARPROT;
wire   [3:0] grp_sound_sender_Pipeline_2_fu_186_m_axi_out_bus_ARQOS;
wire   [3:0] grp_sound_sender_Pipeline_2_fu_186_m_axi_out_bus_ARREGION;
wire   [0:0] grp_sound_sender_Pipeline_2_fu_186_m_axi_out_bus_ARUSER;
wire    grp_sound_sender_Pipeline_2_fu_186_m_axi_out_bus_RREADY;
wire    grp_sound_sender_Pipeline_2_fu_186_m_axi_out_bus_BREADY;
wire   [3:0] grp_sound_sender_Pipeline_2_fu_186_data_buf_address0;
wire    grp_sound_sender_Pipeline_2_fu_186_data_buf_ce0;
reg    out_bus_AWVALID;
wire    out_bus_AWREADY;
reg   [31:0] out_bus_AWADDR;
reg   [31:0] out_bus_AWLEN;
reg    out_bus_WVALID;
wire    out_bus_WREADY;
reg   [31:0] out_bus_WDATA;
reg   [3:0] out_bus_WSTRB;
wire    out_bus_ARREADY;
wire    out_bus_RVALID;
wire   [31:0] out_bus_RDATA;
wire   [8:0] out_bus_RFIFONUM;
wire    out_bus_BVALID;
reg    out_bus_BREADY;
reg   [0:0] ap_phi_mux_empty_17_phi_fu_159_p6;
reg   [0:0] empty_17_reg_155;
reg    ap_block_state16;
reg    ap_block_state10_io;
reg    grp_sound_sender_Pipeline_VITIS_LOOP_48_1_fu_171_ap_start_reg;
wire    ap_CS_fsm_state2;
reg    grp_sound_sender_Pipeline_2_fu_186_ap_start_reg;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state5;
wire   [31:0] zext_ln64_fu_245_p1;
wire   [15:0] grp_fu_194_p2;
wire   [12:0] shl_ln_fu_219_p3;
wire   [12:0] or_ln64_fu_227_p2;
wire  signed [26:0] sext_ln64_fu_241_p1;
wire   [8:0] add_ln65_fu_256_p2;
wire   [0:0] icmp_ln67_fu_261_p2;
reg   [20:0] ap_NS_fsm;
wire    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
reg    ap_ST_fsm_state10_blk;
reg    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
reg    ap_ST_fsm_state16_blk;
reg    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
wire    ap_ST_fsm_state19_blk;
wire    ap_ST_fsm_state20_blk;
wire    ap_ST_fsm_state21_blk;
wire    regslice_both_in_bus_V_data_V_U_apdone_blk;
wire   [31:0] in_bus_TDATA_int_regslice;
wire    in_bus_TVALID_int_regslice;
reg    in_bus_TREADY_int_regslice;
wire    regslice_both_in_bus_V_data_V_U_ack_in;
wire    regslice_both_in_bus_V_keep_V_U_apdone_blk;
wire   [3:0] in_bus_TKEEP_int_regslice;
wire    regslice_both_in_bus_V_keep_V_U_vld_out;
wire    regslice_both_in_bus_V_keep_V_U_ack_in;
wire    regslice_both_in_bus_V_strb_V_U_apdone_blk;
wire   [3:0] in_bus_TSTRB_int_regslice;
wire    regslice_both_in_bus_V_strb_V_U_vld_out;
wire    regslice_both_in_bus_V_strb_V_U_ack_in;
wire    regslice_both_in_bus_V_user_V_U_apdone_blk;
wire   [15:0] in_bus_TUSER_int_regslice;
wire    regslice_both_in_bus_V_user_V_U_vld_out;
wire    regslice_both_in_bus_V_user_V_U_ack_in;
wire    regslice_both_in_bus_V_last_V_U_apdone_blk;
wire   [0:0] in_bus_TLAST_int_regslice;
wire    regslice_both_in_bus_V_last_V_U_vld_out;
wire    regslice_both_in_bus_V_last_V_U_ack_in;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 burst_count_reg = 9'd0;
#0 test_irq_cnt = 16'd0;
#0 ap_CS_fsm = 21'd1;
#0 grp_sound_sender_Pipeline_VITIS_LOOP_48_1_fu_171_ap_start_reg = 1'b0;
#0 grp_sound_sender_Pipeline_2_fu_186_ap_start_reg = 1'b0;
end

sound_sender_data_buf_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
data_buf_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(data_buf_address0),
    .ce0(data_buf_ce0),
    .we0(data_buf_we0),
    .d0(grp_sound_sender_Pipeline_VITIS_LOOP_48_1_fu_171_data_buf_d0),
    .q0(data_buf_q0)
);

sound_sender_sound_sender_Pipeline_VITIS_LOOP_48_1 grp_sound_sender_Pipeline_VITIS_LOOP_48_1_fu_171(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_sound_sender_Pipeline_VITIS_LOOP_48_1_fu_171_ap_start),
    .ap_done(grp_sound_sender_Pipeline_VITIS_LOOP_48_1_fu_171_ap_done),
    .ap_idle(grp_sound_sender_Pipeline_VITIS_LOOP_48_1_fu_171_ap_idle),
    .ap_ready(grp_sound_sender_Pipeline_VITIS_LOOP_48_1_fu_171_ap_ready),
    .in_bus_TVALID(in_bus_TVALID_int_regslice),
    .in_bus_TDATA(in_bus_TDATA_int_regslice),
    .in_bus_TREADY(grp_sound_sender_Pipeline_VITIS_LOOP_48_1_fu_171_in_bus_TREADY),
    .in_bus_TKEEP(in_bus_TKEEP_int_regslice),
    .in_bus_TSTRB(in_bus_TSTRB_int_regslice),
    .in_bus_TUSER(in_bus_TUSER_int_regslice),
    .in_bus_TLAST(in_bus_TLAST_int_regslice),
    .data_buf_address0(grp_sound_sender_Pipeline_VITIS_LOOP_48_1_fu_171_data_buf_address0),
    .data_buf_ce0(grp_sound_sender_Pipeline_VITIS_LOOP_48_1_fu_171_data_buf_ce0),
    .data_buf_we0(grp_sound_sender_Pipeline_VITIS_LOOP_48_1_fu_171_data_buf_we0),
    .data_buf_d0(grp_sound_sender_Pipeline_VITIS_LOOP_48_1_fu_171_data_buf_d0)
);

sound_sender_sound_sender_Pipeline_2 grp_sound_sender_Pipeline_2_fu_186(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_sound_sender_Pipeline_2_fu_186_ap_start),
    .ap_done(grp_sound_sender_Pipeline_2_fu_186_ap_done),
    .ap_idle(grp_sound_sender_Pipeline_2_fu_186_ap_idle),
    .ap_ready(grp_sound_sender_Pipeline_2_fu_186_ap_ready),
    .m_axi_out_bus_AWVALID(grp_sound_sender_Pipeline_2_fu_186_m_axi_out_bus_AWVALID),
    .m_axi_out_bus_AWREADY(out_bus_AWREADY),
    .m_axi_out_bus_AWADDR(grp_sound_sender_Pipeline_2_fu_186_m_axi_out_bus_AWADDR),
    .m_axi_out_bus_AWID(grp_sound_sender_Pipeline_2_fu_186_m_axi_out_bus_AWID),
    .m_axi_out_bus_AWLEN(grp_sound_sender_Pipeline_2_fu_186_m_axi_out_bus_AWLEN),
    .m_axi_out_bus_AWSIZE(grp_sound_sender_Pipeline_2_fu_186_m_axi_out_bus_AWSIZE),
    .m_axi_out_bus_AWBURST(grp_sound_sender_Pipeline_2_fu_186_m_axi_out_bus_AWBURST),
    .m_axi_out_bus_AWLOCK(grp_sound_sender_Pipeline_2_fu_186_m_axi_out_bus_AWLOCK),
    .m_axi_out_bus_AWCACHE(grp_sound_sender_Pipeline_2_fu_186_m_axi_out_bus_AWCACHE),
    .m_axi_out_bus_AWPROT(grp_sound_sender_Pipeline_2_fu_186_m_axi_out_bus_AWPROT),
    .m_axi_out_bus_AWQOS(grp_sound_sender_Pipeline_2_fu_186_m_axi_out_bus_AWQOS),
    .m_axi_out_bus_AWREGION(grp_sound_sender_Pipeline_2_fu_186_m_axi_out_bus_AWREGION),
    .m_axi_out_bus_AWUSER(grp_sound_sender_Pipeline_2_fu_186_m_axi_out_bus_AWUSER),
    .m_axi_out_bus_WVALID(grp_sound_sender_Pipeline_2_fu_186_m_axi_out_bus_WVALID),
    .m_axi_out_bus_WREADY(out_bus_WREADY),
    .m_axi_out_bus_WDATA(grp_sound_sender_Pipeline_2_fu_186_m_axi_out_bus_WDATA),
    .m_axi_out_bus_WSTRB(grp_sound_sender_Pipeline_2_fu_186_m_axi_out_bus_WSTRB),
    .m_axi_out_bus_WLAST(grp_sound_sender_Pipeline_2_fu_186_m_axi_out_bus_WLAST),
    .m_axi_out_bus_WID(grp_sound_sender_Pipeline_2_fu_186_m_axi_out_bus_WID),
    .m_axi_out_bus_WUSER(grp_sound_sender_Pipeline_2_fu_186_m_axi_out_bus_WUSER),
    .m_axi_out_bus_ARVALID(grp_sound_sender_Pipeline_2_fu_186_m_axi_out_bus_ARVALID),
    .m_axi_out_bus_ARREADY(1'b0),
    .m_axi_out_bus_ARADDR(grp_sound_sender_Pipeline_2_fu_186_m_axi_out_bus_ARADDR),
    .m_axi_out_bus_ARID(grp_sound_sender_Pipeline_2_fu_186_m_axi_out_bus_ARID),
    .m_axi_out_bus_ARLEN(grp_sound_sender_Pipeline_2_fu_186_m_axi_out_bus_ARLEN),
    .m_axi_out_bus_ARSIZE(grp_sound_sender_Pipeline_2_fu_186_m_axi_out_bus_ARSIZE),
    .m_axi_out_bus_ARBURST(grp_sound_sender_Pipeline_2_fu_186_m_axi_out_bus_ARBURST),
    .m_axi_out_bus_ARLOCK(grp_sound_sender_Pipeline_2_fu_186_m_axi_out_bus_ARLOCK),
    .m_axi_out_bus_ARCACHE(grp_sound_sender_Pipeline_2_fu_186_m_axi_out_bus_ARCACHE),
    .m_axi_out_bus_ARPROT(grp_sound_sender_Pipeline_2_fu_186_m_axi_out_bus_ARPROT),
    .m_axi_out_bus_ARQOS(grp_sound_sender_Pipeline_2_fu_186_m_axi_out_bus_ARQOS),
    .m_axi_out_bus_ARREGION(grp_sound_sender_Pipeline_2_fu_186_m_axi_out_bus_ARREGION),
    .m_axi_out_bus_ARUSER(grp_sound_sender_Pipeline_2_fu_186_m_axi_out_bus_ARUSER),
    .m_axi_out_bus_RVALID(1'b0),
    .m_axi_out_bus_RREADY(grp_sound_sender_Pipeline_2_fu_186_m_axi_out_bus_RREADY),
    .m_axi_out_bus_RDATA(32'd0),
    .m_axi_out_bus_RLAST(1'b0),
    .m_axi_out_bus_RID(1'd0),
    .m_axi_out_bus_RFIFONUM(9'd0),
    .m_axi_out_bus_RUSER(1'd0),
    .m_axi_out_bus_RRESP(2'd0),
    .m_axi_out_bus_BVALID(out_bus_BVALID),
    .m_axi_out_bus_BREADY(grp_sound_sender_Pipeline_2_fu_186_m_axi_out_bus_BREADY),
    .m_axi_out_bus_BRESP(2'd0),
    .m_axi_out_bus_BID(1'd0),
    .m_axi_out_bus_BUSER(1'd0),
    .zext_ln64(or_ln_reg_301),
    .data_buf_address0(grp_sound_sender_Pipeline_2_fu_186_data_buf_address0),
    .data_buf_ce0(grp_sound_sender_Pipeline_2_fu_186_data_buf_ce0),
    .data_buf_q0(data_buf_q0)
);

sound_sender_out_bus_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 5 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_OUT_BUS_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_OUT_BUS_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_OUT_BUS_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_OUT_BUS_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_OUT_BUS_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_OUT_BUS_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_OUT_BUS_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_OUT_BUS_BUSER_WIDTH ),
    .C_TARGET_ADDR( C_M_AXI_OUT_BUS_TARGET_ADDR ),
    .C_USER_VALUE( C_M_AXI_OUT_BUS_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_OUT_BUS_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_OUT_BUS_CACHE_VALUE ),
    .USER_RFIFONUM_WIDTH( 9 ),
    .USER_DW( 32 ),
    .USER_AW( 32 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ))
out_bus_m_axi_U(
    .AWVALID(m_axi_out_bus_AWVALID),
    .AWREADY(m_axi_out_bus_AWREADY),
    .AWADDR(m_axi_out_bus_AWADDR),
    .AWID(m_axi_out_bus_AWID),
    .AWLEN(m_axi_out_bus_AWLEN),
    .AWSIZE(m_axi_out_bus_AWSIZE),
    .AWBURST(m_axi_out_bus_AWBURST),
    .AWLOCK(m_axi_out_bus_AWLOCK),
    .AWCACHE(m_axi_out_bus_AWCACHE),
    .AWPROT(m_axi_out_bus_AWPROT),
    .AWQOS(m_axi_out_bus_AWQOS),
    .AWREGION(m_axi_out_bus_AWREGION),
    .AWUSER(m_axi_out_bus_AWUSER),
    .WVALID(m_axi_out_bus_WVALID),
    .WREADY(m_axi_out_bus_WREADY),
    .WDATA(m_axi_out_bus_WDATA),
    .WSTRB(m_axi_out_bus_WSTRB),
    .WLAST(m_axi_out_bus_WLAST),
    .WID(m_axi_out_bus_WID),
    .WUSER(m_axi_out_bus_WUSER),
    .ARVALID(m_axi_out_bus_ARVALID),
    .ARREADY(m_axi_out_bus_ARREADY),
    .ARADDR(m_axi_out_bus_ARADDR),
    .ARID(m_axi_out_bus_ARID),
    .ARLEN(m_axi_out_bus_ARLEN),
    .ARSIZE(m_axi_out_bus_ARSIZE),
    .ARBURST(m_axi_out_bus_ARBURST),
    .ARLOCK(m_axi_out_bus_ARLOCK),
    .ARCACHE(m_axi_out_bus_ARCACHE),
    .ARPROT(m_axi_out_bus_ARPROT),
    .ARQOS(m_axi_out_bus_ARQOS),
    .ARREGION(m_axi_out_bus_ARREGION),
    .ARUSER(m_axi_out_bus_ARUSER),
    .RVALID(m_axi_out_bus_RVALID),
    .RREADY(m_axi_out_bus_RREADY),
    .RDATA(m_axi_out_bus_RDATA),
    .RLAST(m_axi_out_bus_RLAST),
    .RID(m_axi_out_bus_RID),
    .RUSER(m_axi_out_bus_RUSER),
    .RRESP(m_axi_out_bus_RRESP),
    .BVALID(m_axi_out_bus_BVALID),
    .BREADY(m_axi_out_bus_BREADY),
    .BRESP(m_axi_out_bus_BRESP),
    .BID(m_axi_out_bus_BID),
    .BUSER(m_axi_out_bus_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(1'b0),
    .I_ARREADY(out_bus_ARREADY),
    .I_ARADDR(32'd0),
    .I_ARLEN(32'd0),
    .I_RVALID(out_bus_RVALID),
    .I_RREADY(1'b0),
    .I_RDATA(out_bus_RDATA),
    .I_RFIFONUM(out_bus_RFIFONUM),
    .I_AWVALID(out_bus_AWVALID),
    .I_AWREADY(out_bus_AWREADY),
    .I_AWADDR(out_bus_AWADDR),
    .I_AWLEN(out_bus_AWLEN),
    .I_WVALID(out_bus_WVALID),
    .I_WREADY(out_bus_WREADY),
    .I_WDATA(out_bus_WDATA),
    .I_WSTRB(out_bus_WSTRB),
    .I_BVALID(out_bus_BVALID),
    .I_BREADY(out_bus_BREADY)
);

sound_sender_regslice_both #(
    .DataWidth( 32 ))
regslice_both_in_bus_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_bus_TDATA),
    .vld_in(in_bus_TVALID),
    .ack_in(regslice_both_in_bus_V_data_V_U_ack_in),
    .data_out(in_bus_TDATA_int_regslice),
    .vld_out(in_bus_TVALID_int_regslice),
    .ack_out(in_bus_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_bus_V_data_V_U_apdone_blk)
);

sound_sender_regslice_both #(
    .DataWidth( 4 ))
regslice_both_in_bus_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_bus_TKEEP),
    .vld_in(in_bus_TVALID),
    .ack_in(regslice_both_in_bus_V_keep_V_U_ack_in),
    .data_out(in_bus_TKEEP_int_regslice),
    .vld_out(regslice_both_in_bus_V_keep_V_U_vld_out),
    .ack_out(in_bus_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_bus_V_keep_V_U_apdone_blk)
);

sound_sender_regslice_both #(
    .DataWidth( 4 ))
regslice_both_in_bus_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_bus_TSTRB),
    .vld_in(in_bus_TVALID),
    .ack_in(regslice_both_in_bus_V_strb_V_U_ack_in),
    .data_out(in_bus_TSTRB_int_regslice),
    .vld_out(regslice_both_in_bus_V_strb_V_U_vld_out),
    .ack_out(in_bus_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_bus_V_strb_V_U_apdone_blk)
);

sound_sender_regslice_both #(
    .DataWidth( 16 ))
regslice_both_in_bus_V_user_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_bus_TUSER),
    .vld_in(in_bus_TVALID),
    .ack_in(regslice_both_in_bus_V_user_V_U_ack_in),
    .data_out(in_bus_TUSER_int_regslice),
    .vld_out(regslice_both_in_bus_V_user_V_U_vld_out),
    .ack_out(in_bus_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_bus_V_user_V_U_apdone_blk)
);

sound_sender_regslice_both #(
    .DataWidth( 1 ))
regslice_both_in_bus_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_bus_TLAST),
    .vld_in(in_bus_TVALID),
    .ack_in(regslice_both_in_bus_V_last_V_U_ack_in),
    .data_out(in_bus_TLAST_int_regslice),
    .vld_out(regslice_both_in_bus_V_last_V_U_vld_out),
    .ack_out(in_bus_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_bus_V_last_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_sound_sender_Pipeline_2_fu_186_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state4)) begin
            grp_sound_sender_Pipeline_2_fu_186_ap_start_reg <= 1'b1;
        end else if ((grp_sound_sender_Pipeline_2_fu_186_ap_ready == 1'b1)) begin
            grp_sound_sender_Pipeline_2_fu_186_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_sound_sender_Pipeline_VITIS_LOOP_48_1_fu_171_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_sound_sender_Pipeline_VITIS_LOOP_48_1_fu_171_ap_start_reg <= 1'b1;
        end else if ((grp_sound_sender_Pipeline_VITIS_LOOP_48_1_fu_171_ap_ready == 1'b1)) begin
            grp_sound_sender_Pipeline_VITIS_LOOP_48_1_fu_171_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state10_io) | (out_bus_BVALID == 1'b0)) & ~(select_ln67_reg_311 == 9'd200) & ~(select_ln67_reg_311 == 9'd0) & (1'b1 == ap_CS_fsm_state10))) begin
        empty_17_reg_155 <= 1'd0;
    end else if (((~(((out_bus_BVALID == 1'b0) & (select_ln67_reg_311 == 9'd200)) | ((out_bus_BVALID == 1'b0) & (select_ln67_reg_311 == 9'd0))) & (1'b1 == ap_CS_fsm_state16) & (select_ln67_reg_311 == 9'd200)) | (~(((out_bus_BVALID == 1'b0) & (select_ln67_reg_311 == 9'd200)) | ((out_bus_BVALID == 1'b0) & (select_ln67_reg_311 == 9'd0))) & (1'b1 == ap_CS_fsm_state16) & (select_ln67_reg_311 == 9'd0)))) begin
        empty_17_reg_155 <= 1'd1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        burst_count_reg <= select_ln67_fu_267_p3;
        select_ln67_reg_311 <= select_ln67_fu_267_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        or_ln_reg_301[12 : 4] <= or_ln_fu_233_p3[12 : 4];
    end
end

always @ (posedge ap_clk) begin
    if (((~((1'b1 == ap_block_state10_io) | (out_bus_BVALID == 1'b0)) & (1'b1 == ap_CS_fsm_state10) & (select_ln67_reg_311 == 9'd200)) | (~((1'b1 == ap_block_state10_io) | (out_bus_BVALID == 1'b0)) & (1'b1 == ap_CS_fsm_state10) & (select_ln67_reg_311 == 9'd0)))) begin
        test_irq_cnt <= grp_fu_194_p2;
    end
end

always @ (*) begin
    if (((1'b1 == ap_block_state10_io) | (out_bus_BVALID == 1'b0))) begin
        ap_ST_fsm_state10_blk = 1'b1;
    end else begin
        ap_ST_fsm_state10_blk = 1'b0;
    end
end

always @ (*) begin
    if ((out_bus_WREADY == 1'b0)) begin
        ap_ST_fsm_state11_blk = 1'b1;
    end else begin
        ap_ST_fsm_state11_blk = 1'b0;
    end
end

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

always @ (*) begin
    if ((((out_bus_BVALID == 1'b0) & (select_ln67_reg_311 == 9'd200)) | ((out_bus_BVALID == 1'b0) & (select_ln67_reg_311 == 9'd0)))) begin
        ap_ST_fsm_state16_blk = 1'b1;
    end else begin
        ap_ST_fsm_state16_blk = 1'b0;
    end
end

always @ (*) begin
    if ((out_bus_WREADY == 1'b0)) begin
        ap_ST_fsm_state17_blk = 1'b1;
    end else begin
        ap_ST_fsm_state17_blk = 1'b0;
    end
end

assign ap_ST_fsm_state18_blk = 1'b0;

assign ap_ST_fsm_state19_blk = 1'b0;

assign ap_ST_fsm_state1_blk = 1'b0;

assign ap_ST_fsm_state20_blk = 1'b0;

assign ap_ST_fsm_state21_blk = 1'b0;

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if (((out_bus_AWREADY == 1'b0) | (grp_sound_sender_Pipeline_VITIS_LOOP_48_1_fu_171_ap_done == 1'b0))) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if ((grp_sound_sender_Pipeline_2_fu_186_ap_done == 1'b0)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state16) & (select_ln67_reg_311 == 9'd200)) | ((1'b1 == ap_CS_fsm_state16) & (select_ln67_reg_311 == 9'd0)))) begin
        ap_phi_mux_empty_17_phi_fu_159_p6 = 1'd1;
    end else begin
        ap_phi_mux_empty_17_phi_fu_159_p6 = empty_17_reg_155;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        data_buf_address0 = grp_sound_sender_Pipeline_2_fu_186_data_buf_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        data_buf_address0 = grp_sound_sender_Pipeline_VITIS_LOOP_48_1_fu_171_data_buf_address0;
    end else begin
        data_buf_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        data_buf_ce0 = grp_sound_sender_Pipeline_2_fu_186_data_buf_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        data_buf_ce0 = grp_sound_sender_Pipeline_VITIS_LOOP_48_1_fu_171_data_buf_ce0;
    end else begin
        data_buf_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        data_buf_we0 = grp_sound_sender_Pipeline_VITIS_LOOP_48_1_fu_171_data_buf_we0;
    end else begin
        data_buf_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        in_bus_TREADY_int_regslice = grp_sound_sender_Pipeline_VITIS_LOOP_48_1_fu_171_in_bus_TREADY;
    end else begin
        in_bus_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((~(((out_bus_BVALID == 1'b0) & (select_ln67_reg_311 == 9'd200)) | ((out_bus_BVALID == 1'b0) & (select_ln67_reg_311 == 9'd0))) & (1'b1 == ap_CS_fsm_state16))) begin
        interrupt_out_ap_vld = 1'b1;
    end else begin
        interrupt_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((~((1'b1 == ap_block_state10_io) | (out_bus_BVALID == 1'b0)) & (1'b1 == ap_CS_fsm_state10) & (select_ln67_reg_311 == 9'd200)) | (~((1'b1 == ap_block_state10_io) | (out_bus_BVALID == 1'b0)) & (1'b1 == ap_CS_fsm_state10) & (select_ln67_reg_311 == 9'd0)))) begin
        out_bus_AWADDR = 32'd131072000;
    end else if ((~((out_bus_AWREADY == 1'b0) | (grp_sound_sender_Pipeline_VITIS_LOOP_48_1_fu_171_ap_done == 1'b0)) & (1'b1 == ap_CS_fsm_state3))) begin
        out_bus_AWADDR = zext_ln64_fu_245_p1;
    end else if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        out_bus_AWADDR = grp_sound_sender_Pipeline_2_fu_186_m_axi_out_bus_AWADDR;
    end else begin
        out_bus_AWADDR = 'bx;
    end
end

always @ (*) begin
    if (((~((1'b1 == ap_block_state10_io) | (out_bus_BVALID == 1'b0)) & (1'b1 == ap_CS_fsm_state10) & (select_ln67_reg_311 == 9'd200)) | (~((1'b1 == ap_block_state10_io) | (out_bus_BVALID == 1'b0)) & (1'b1 == ap_CS_fsm_state10) & (select_ln67_reg_311 == 9'd0)))) begin
        out_bus_AWLEN = 32'd1;
    end else if ((~((out_bus_AWREADY == 1'b0) | (grp_sound_sender_Pipeline_VITIS_LOOP_48_1_fu_171_ap_done == 1'b0)) & (1'b1 == ap_CS_fsm_state3))) begin
        out_bus_AWLEN = 32'd16;
    end else if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        out_bus_AWLEN = grp_sound_sender_Pipeline_2_fu_186_m_axi_out_bus_AWLEN;
    end else begin
        out_bus_AWLEN = 'bx;
    end
end

always @ (*) begin
    if (((~((out_bus_AWREADY == 1'b0) | (grp_sound_sender_Pipeline_VITIS_LOOP_48_1_fu_171_ap_done == 1'b0)) & (1'b1 == ap_CS_fsm_state3)) | (~((1'b1 == ap_block_state10_io) | (out_bus_BVALID == 1'b0)) & (1'b1 == ap_CS_fsm_state10) & (select_ln67_reg_311 == 9'd200)) | (~((1'b1 == ap_block_state10_io) | (out_bus_BVALID == 1'b0)) & (1'b1 == ap_CS_fsm_state10) & (select_ln67_reg_311 == 9'd0)))) begin
        out_bus_AWVALID = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        out_bus_AWVALID = grp_sound_sender_Pipeline_2_fu_186_m_axi_out_bus_AWVALID;
    end else begin
        out_bus_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if (((~((1'b1 == ap_block_state10_io) | (out_bus_BVALID == 1'b0)) & (1'b1 == ap_CS_fsm_state10)) | (~(((out_bus_BVALID == 1'b0) & (select_ln67_reg_311 == 9'd200)) | ((out_bus_BVALID == 1'b0) & (select_ln67_reg_311 == 9'd0))) & (1'b1 == ap_CS_fsm_state16) & (select_ln67_reg_311 == 9'd200)) | (~(((out_bus_BVALID == 1'b0) & (select_ln67_reg_311 == 9'd200)) | ((out_bus_BVALID == 1'b0) & (select_ln67_reg_311 == 9'd0))) & (1'b1 == ap_CS_fsm_state16) & (select_ln67_reg_311 == 9'd0)))) begin
        out_bus_BREADY = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        out_bus_BREADY = grp_sound_sender_Pipeline_2_fu_186_m_axi_out_bus_BREADY;
    end else begin
        out_bus_BREADY = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        out_bus_WDATA = 32'd1;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        out_bus_WDATA = 32'd0;
    end else if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        out_bus_WDATA = grp_sound_sender_Pipeline_2_fu_186_m_axi_out_bus_WDATA;
    end else begin
        out_bus_WDATA = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state17))) begin
        out_bus_WSTRB = 4'd15;
    end else if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        out_bus_WSTRB = grp_sound_sender_Pipeline_2_fu_186_m_axi_out_bus_WSTRB;
    end else begin
        out_bus_WSTRB = 'bx;
    end
end

always @ (*) begin
    if ((((out_bus_WREADY == 1'b1) & (1'b1 == ap_CS_fsm_state11)) | ((out_bus_WREADY == 1'b1) & (1'b1 == ap_CS_fsm_state17)))) begin
        out_bus_WVALID = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        out_bus_WVALID = grp_sound_sender_Pipeline_2_fu_186_m_axi_out_bus_WVALID;
    end else begin
        out_bus_WVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | ((1'b1 == ap_CS_fsm_state10) & (select_ln67_reg_311 == 9'd200)) | ((1'b1 == ap_CS_fsm_state10) & (select_ln67_reg_311 == 9'd0)))) begin
        out_bus_blk_n_AW = m_axi_out_bus_AWREADY;
    end else begin
        out_bus_blk_n_AW = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | ((1'b1 == ap_CS_fsm_state16) & (select_ln67_reg_311 == 9'd200)) | ((1'b1 == ap_CS_fsm_state16) & (select_ln67_reg_311 == 9'd0)))) begin
        out_bus_blk_n_B = m_axi_out_bus_BVALID;
    end else begin
        out_bus_blk_n_B = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state17))) begin
        out_bus_blk_n_W = m_axi_out_bus_WREADY;
    end else begin
        out_bus_blk_n_W = 1'b1;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if ((~((out_bus_AWREADY == 1'b0) | (grp_sound_sender_Pipeline_VITIS_LOOP_48_1_fu_171_ap_done == 1'b0)) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((1'b1 == ap_CS_fsm_state5) & (grp_sound_sender_Pipeline_2_fu_186_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            if ((~((1'b1 == ap_block_state10_io) | (out_bus_BVALID == 1'b0)) & (1'b1 == ap_CS_fsm_state10) & (select_ln67_reg_311 == 9'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end else if ((~((1'b1 == ap_block_state10_io) | (out_bus_BVALID == 1'b0)) & ~(select_ln67_reg_311 == 9'd200) & ~(select_ln67_reg_311 == 9'd0) & (1'b1 == ap_CS_fsm_state10))) begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end else if ((~((1'b1 == ap_block_state10_io) | (out_bus_BVALID == 1'b0)) & (1'b1 == ap_CS_fsm_state10) & (select_ln67_reg_311 == 9'd200))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state11 : begin
            if (((out_bus_WREADY == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            if ((~(((out_bus_BVALID == 1'b0) & (select_ln67_reg_311 == 9'd200)) | ((out_bus_BVALID == 1'b0) & (select_ln67_reg_311 == 9'd0))) & (1'b1 == ap_CS_fsm_state16))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end
        end
        ap_ST_fsm_state17 : begin
            if (((out_bus_WREADY == 1'b1) & (1'b1 == ap_CS_fsm_state17))) begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln65_fu_256_p2 = (burst_count_reg + 9'd1);

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state10_io = (((out_bus_AWREADY == 1'b0) & (select_ln67_reg_311 == 9'd200)) | ((out_bus_AWREADY == 1'b0) & (select_ln67_reg_311 == 9'd0)));
end

always @ (*) begin
    ap_block_state16 = (((out_bus_BVALID == 1'b0) & (select_ln67_reg_311 == 9'd200)) | ((out_bus_BVALID == 1'b0) & (select_ln67_reg_311 == 9'd0)));
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign grp_fu_194_p2 = (test_irq_cnt + 16'd1);

assign grp_sound_sender_Pipeline_2_fu_186_ap_start = grp_sound_sender_Pipeline_2_fu_186_ap_start_reg;

assign grp_sound_sender_Pipeline_VITIS_LOOP_48_1_fu_171_ap_start = grp_sound_sender_Pipeline_VITIS_LOOP_48_1_fu_171_ap_start_reg;

assign icmp_ln67_fu_261_p2 = ((add_ln65_fu_256_p2 > 9'd399) ? 1'b1 : 1'b0);

assign in_bus_TREADY = regslice_both_in_bus_V_data_V_U_ack_in;

assign interrupt_out = ap_phi_mux_empty_17_phi_fu_159_p6;

assign or_ln64_fu_227_p2 = (shl_ln_fu_219_p3 | 13'd1);

assign or_ln_fu_233_p3 = {{10'd640}, {or_ln64_fu_227_p2}};

assign select_ln67_fu_267_p3 = ((icmp_ln67_fu_261_p2[0:0] == 1'b1) ? 9'd0 : add_ln65_fu_256_p2);

assign sext_ln64_fu_241_p1 = or_ln_fu_233_p3;

assign shl_ln_fu_219_p3 = {{burst_count_reg}, {4'd0}};

assign zext_ln64_fu_245_p1 = $unsigned(sext_ln64_fu_241_p1);

always @ (posedge ap_clk) begin
    or_ln_reg_301[3:0] <= 4'b0001;
    or_ln_reg_301[22:13] <= 10'b1010000000;
end


reg find_kernel_block = 0;
// synthesis translate_off
`include "sound_sender_hls_deadlock_kernel_monitor_top.vh"
// synthesis translate_on

endmodule //sound_sender

