// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module sound_sender_sound_sender_Pipeline_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_out_bus_AWVALID,
        m_axi_out_bus_AWREADY,
        m_axi_out_bus_AWADDR,
        m_axi_out_bus_AWID,
        m_axi_out_bus_AWLEN,
        m_axi_out_bus_AWSIZE,
        m_axi_out_bus_AWBURST,
        m_axi_out_bus_AWLOCK,
        m_axi_out_bus_AWCACHE,
        m_axi_out_bus_AWPROT,
        m_axi_out_bus_AWQOS,
        m_axi_out_bus_AWREGION,
        m_axi_out_bus_AWUSER,
        m_axi_out_bus_WVALID,
        m_axi_out_bus_WREADY,
        m_axi_out_bus_WDATA,
        m_axi_out_bus_WSTRB,
        m_axi_out_bus_WLAST,
        m_axi_out_bus_WID,
        m_axi_out_bus_WUSER,
        m_axi_out_bus_ARVALID,
        m_axi_out_bus_ARREADY,
        m_axi_out_bus_ARADDR,
        m_axi_out_bus_ARID,
        m_axi_out_bus_ARLEN,
        m_axi_out_bus_ARSIZE,
        m_axi_out_bus_ARBURST,
        m_axi_out_bus_ARLOCK,
        m_axi_out_bus_ARCACHE,
        m_axi_out_bus_ARPROT,
        m_axi_out_bus_ARQOS,
        m_axi_out_bus_ARREGION,
        m_axi_out_bus_ARUSER,
        m_axi_out_bus_RVALID,
        m_axi_out_bus_RREADY,
        m_axi_out_bus_RDATA,
        m_axi_out_bus_RLAST,
        m_axi_out_bus_RID,
        m_axi_out_bus_RFIFONUM,
        m_axi_out_bus_RUSER,
        m_axi_out_bus_RRESP,
        m_axi_out_bus_BVALID,
        m_axi_out_bus_BREADY,
        m_axi_out_bus_BRESP,
        m_axi_out_bus_BID,
        m_axi_out_bus_BUSER,
        zext_ln64,
        data_buf_address0,
        data_buf_ce0,
        data_buf_q0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_out_bus_AWVALID;
input   m_axi_out_bus_AWREADY;
output  [31:0] m_axi_out_bus_AWADDR;
output  [0:0] m_axi_out_bus_AWID;
output  [31:0] m_axi_out_bus_AWLEN;
output  [2:0] m_axi_out_bus_AWSIZE;
output  [1:0] m_axi_out_bus_AWBURST;
output  [1:0] m_axi_out_bus_AWLOCK;
output  [3:0] m_axi_out_bus_AWCACHE;
output  [2:0] m_axi_out_bus_AWPROT;
output  [3:0] m_axi_out_bus_AWQOS;
output  [3:0] m_axi_out_bus_AWREGION;
output  [0:0] m_axi_out_bus_AWUSER;
output   m_axi_out_bus_WVALID;
input   m_axi_out_bus_WREADY;
output  [31:0] m_axi_out_bus_WDATA;
output  [3:0] m_axi_out_bus_WSTRB;
output   m_axi_out_bus_WLAST;
output  [0:0] m_axi_out_bus_WID;
output  [0:0] m_axi_out_bus_WUSER;
output   m_axi_out_bus_ARVALID;
input   m_axi_out_bus_ARREADY;
output  [31:0] m_axi_out_bus_ARADDR;
output  [0:0] m_axi_out_bus_ARID;
output  [31:0] m_axi_out_bus_ARLEN;
output  [2:0] m_axi_out_bus_ARSIZE;
output  [1:0] m_axi_out_bus_ARBURST;
output  [1:0] m_axi_out_bus_ARLOCK;
output  [3:0] m_axi_out_bus_ARCACHE;
output  [2:0] m_axi_out_bus_ARPROT;
output  [3:0] m_axi_out_bus_ARQOS;
output  [3:0] m_axi_out_bus_ARREGION;
output  [0:0] m_axi_out_bus_ARUSER;
input   m_axi_out_bus_RVALID;
output   m_axi_out_bus_RREADY;
input  [31:0] m_axi_out_bus_RDATA;
input   m_axi_out_bus_RLAST;
input  [0:0] m_axi_out_bus_RID;
input  [8:0] m_axi_out_bus_RFIFONUM;
input  [0:0] m_axi_out_bus_RUSER;
input  [1:0] m_axi_out_bus_RRESP;
input   m_axi_out_bus_BVALID;
output   m_axi_out_bus_BREADY;
input  [1:0] m_axi_out_bus_BRESP;
input  [0:0] m_axi_out_bus_BID;
input  [0:0] m_axi_out_bus_BUSER;
input  [22:0] zext_ln64;
output  [3:0] data_buf_address0;
output   data_buf_ce0;
input  [31:0] data_buf_q0;

reg ap_idle;
reg m_axi_out_bus_WVALID;
reg data_buf_ce0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] exitcond1_fu_93_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    out_bus_blk_n_W;
wire    ap_block_pp0_stage0;
reg    ap_block_pp0_stage0_11001;
reg   [0:0] exitcond1_reg_136;
reg   [31:0] data_buf_load_reg_150;
reg    ap_condition_exit_pp0_iter1_stage0;
wire   [31:0] loop_index_cast_cast_fu_109_p1;
wire    ap_block_pp0_stage0_01001;
reg   [4:0] loop_index_fu_46;
wire   [4:0] empty_13_fu_99_p2;
wire    ap_loop_init;
reg   [4:0] ap_sig_allocacmp_loop_index_load;
wire   [3:0] empty_14_fu_105_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_done_reg = 1'b0;
end

sound_sender_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((exitcond1_fu_93_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            loop_index_fu_46 <= empty_13_fu_99_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            loop_index_fu_46 <= 5'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        exitcond1_reg_136 <= exitcond1_fu_93_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (exitcond1_reg_136 == 1'd0))) begin
        data_buf_load_reg_150 <= data_buf_q0;
    end
end

always @ (*) begin
    if (((exitcond1_fu_93_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (exitcond1_reg_136 == 1'd1))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_loop_index_load = 5'd0;
    end else begin
        ap_sig_allocacmp_loop_index_load = loop_index_fu_46;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        data_buf_ce0 = 1'b1;
    end else begin
        data_buf_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        m_axi_out_bus_WVALID = 1'b1;
    end else begin
        m_axi_out_bus_WVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        out_bus_blk_n_W = m_axi_out_bus_WREADY;
    end else begin
        out_bus_blk_n_W = 1'b1;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((m_axi_out_bus_WREADY == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((m_axi_out_bus_WREADY == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1));
end

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign data_buf_address0 = loop_index_cast_cast_fu_109_p1;

assign empty_13_fu_99_p2 = (ap_sig_allocacmp_loop_index_load + 5'd1);

assign empty_14_fu_105_p1 = ap_sig_allocacmp_loop_index_load[3:0];

assign exitcond1_fu_93_p2 = ((ap_sig_allocacmp_loop_index_load == 5'd16) ? 1'b1 : 1'b0);

assign loop_index_cast_cast_fu_109_p1 = empty_14_fu_105_p1;

assign m_axi_out_bus_ARADDR = 32'd0;

assign m_axi_out_bus_ARBURST = 2'd0;

assign m_axi_out_bus_ARCACHE = 4'd0;

assign m_axi_out_bus_ARID = 1'd0;

assign m_axi_out_bus_ARLEN = 32'd0;

assign m_axi_out_bus_ARLOCK = 2'd0;

assign m_axi_out_bus_ARPROT = 3'd0;

assign m_axi_out_bus_ARQOS = 4'd0;

assign m_axi_out_bus_ARREGION = 4'd0;

assign m_axi_out_bus_ARSIZE = 3'd0;

assign m_axi_out_bus_ARUSER = 1'd0;

assign m_axi_out_bus_ARVALID = 1'b0;

assign m_axi_out_bus_AWADDR = 32'd0;

assign m_axi_out_bus_AWBURST = 2'd0;

assign m_axi_out_bus_AWCACHE = 4'd0;

assign m_axi_out_bus_AWID = 1'd0;

assign m_axi_out_bus_AWLEN = 32'd0;

assign m_axi_out_bus_AWLOCK = 2'd0;

assign m_axi_out_bus_AWPROT = 3'd0;

assign m_axi_out_bus_AWQOS = 4'd0;

assign m_axi_out_bus_AWREGION = 4'd0;

assign m_axi_out_bus_AWSIZE = 3'd0;

assign m_axi_out_bus_AWUSER = 1'd0;

assign m_axi_out_bus_AWVALID = 1'b0;

assign m_axi_out_bus_BREADY = 1'b0;

assign m_axi_out_bus_RREADY = 1'b0;

assign m_axi_out_bus_WDATA = data_buf_load_reg_150;

assign m_axi_out_bus_WID = 1'd0;

assign m_axi_out_bus_WLAST = 1'b0;

assign m_axi_out_bus_WSTRB = 4'd15;

assign m_axi_out_bus_WUSER = 1'd0;

endmodule //sound_sender_sound_sender_Pipeline_2
